Repository ncloudcamp16-team3/ncamp16-team3-front, pull requests merged in 2025-04, with the labels that each got.

#9 [FEAT]펫스타그램 메인 추가, 화면 크기 변경,footer header z-index 변경
  public/mock/Global/images/haribo.jpg
  public/mock/PetSta/images/badman.svg
  public/mock/PetSta/images/cat1.png
  public/mock/PetSta/images/dog1.png
  public/mock/PetSta/images/dog2.png
  public/mock/PetSta/images/dog3.png
  public/mock/PetSta/images/happyman.svg
  public/mock/PetSta/images/image_20.png
  public/mock/PetSta/videos/happi.mp4
  public/mock/PetSta/videos/happybird.mp4
  src/assets/images/PetStaBookmark.svg
  src/assets/images/PetStaComment.svg
  src/assets/images/PetStaHeart.svg
  src/assets/images/icon1.png
  src/components/Global/Footer.jsx
  src/components/Global/Header.jsx
  src/components/PetSta/FriendIcon.jsx
  src/components/PetSta/FriendList.jsx
  src/components/PetSta/PhotoPost.jsx
  src/components/PetSta/PostBottom.jsx
  src/components/PetSta/PostProfile.jsx
  src/components/PetSta/UserIcon.jsx
  src/components/PetSta/VideoPlayer.jsx
  src/components/PetSta/VideoPost.jsx
  src/css/App.css
  src/mock/PetSta/friends.json
  src/mock/PetSta/posts.json
  src/pages/PetSta/PetSta.jsx
  src/theme/theme.js
Labels: Feat

#10 [FEAT] 회원가입폼 수정, 입력값 값 전달 테스트
  src/components/Sitter/readme.md
  src/components/User/RequiUi.jsx
  src/components/User/Step1.jsx
  src/components/User/Step2.jsx
  src/components/User/Step3.jsx
  src/components/User/Step4.jsx
  src/components/User/Step5.jsx
  src/components/User/readme.md
  src/pages/User/Register.jsx
Labels: Feat

#11 [FIX] 로그인,회원가입 화면 수정
  src/App.jsx
  src/assets/images/User/Google Login.png
  src/assets/images/User/Kakao Login.png
  src/assets/images/User/Naver Login.png
  src/assets/images/User/google-logo.svg
  src/assets/images/User/join-logo.png
  src/assets/images/User/join_logo.png
  src/assets/images/User/kakao-logo.svg
  src/assets/images/User/naver-logo.svg
  src/assets/images/notification2.svg
  src/assets/images/pet-sta-bookmark.svg
  src/assets/images/pet-sta-comment.svg
  src/assets/images/pet-sta-heart.svg
  src/components/PetSta/PostBottom.jsx
  src/components/User/Step1.jsx
  src/components/User/Step2.jsx
  src/components/User/Step3.jsx
  src/components/User/Step4.jsx
  src/components/User/Step5.jsx
  src/css/App.css
  src/pages/User/Login.jsx
  src/pages/User/Register.jsx
Labels: Modify

#16 [FEAT] 관리자 로그인페이지 구현
  src/App.jsx
  src/assets/images/admin.png
  src/assets/images/logo.png
  src/components/Admin/Background.jsx
  src/components/Admin/Login.jsx
  src/css/Admin.css
  src/pages/Admin/Admin.jsx
Labels: Feat

#24 [Modify] 예약,일정,이벤트 각각 다른색 점으로 구분
  src/mock/Calendar/event.json
  src/mock/Calendar/reserves.json
  src/pages/Calender/Calendar.jsx
Labels: Modify

#26 [CHORE] Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Chore

#25 [ADD] 프로필사진 누르면 드롭다운 나오는 기능 구현
  .prettierrc.js
  eslint.config.js
  src/App.jsx
  src/assets/images/Global/modal-bookmark.svg
  src/assets/images/Global/modal-calendar.svg
  src/assets/images/Global/modal-info.svg
  src/assets/images/Global/modal-logout.svg
  src/assets/images/Global/modal-purchase.svg
  src/components/Global/BottomButton.jsx
  src/components/Global/Footer.jsx
  src/components/Global/Header.jsx
  src/components/PetSta/FriendList.jsx
  src/components/PetSta/PhotoPost.jsx
  src/components/PetSta/PostBottom.jsx
  src/components/PetSta/PostProfile.jsx
  src/components/PetSta/UserIcon.jsx
  src/components/PetSta/VideoPlayer.jsx
  src/components/PetSta/VideoPost.jsx
  src/components/User/Step1.jsx
  src/components/User/Step2.jsx
  src/components/User/Step3.jsx
  src/components/User/Step4.jsx
  src/context/Context.jsx
  src/pages/Calender/Calendar.jsx
  src/pages/Main/Main.jsx
  src/pages/PetSta/PostDetail.jsx
  src/pages/User/Login.jsx
  src/pages/User/Register.jsx
Labels: Feat

#31 [ADD]마이페이지 구현
  src/App.jsx
  src/assets/images/User/pet_ex.svg
  src/assets/images/User/petsit_req.svg
  src/components/Global/Header.jsx
  src/components/User/MyPage.jsx
  src/mock/User/pet.json
  src/mock/User/petsitter.json
  src/mock/User/user.json
  src/pages/User/MyPage.jsx
Labels: Feat

#37 [FEAT] 관리자 게시판 화면 5차 수정
  src/App.jsx
  src/components/Admin/DashBoard.jsx
  src/mock/Admin/board.json
Labels: Refactor

#40 [FEAT] 관리자 게시글 목록
  src/App.jsx
  src/components/Admin/AdminContext.jsx
  src/components/Admin/AdminHeader.jsx
  src/components/Admin/DashBoard.jsx
  src/components/Admin/Layout.jsx
  src/components/Admin/PostDetail.jsx
  src/mock/Admin/board.json
  src/pages/Admin/AdminPostDetail.jsx
Labels: Feat

#51 [FEAT] 펫시터 리스트 화면
  src/App.jsx
  src/components/Admin/PetsitterList.jsx
  src/mock/Admin/petsitter.json
  src/pages/Admin/AdminPetsitterList.jsx
Labels: Feat

#60 [MODIFY] 캘린더 컴포넌트 수정
  index.html
  package-lock.json
  package.json
  src/components/Calender/DaumPost.jsx
  src/components/Calender/ScheduleFormCard.jsx
  src/css/calendar/cal.css
  src/pages/Calender/Calendar.jsx
Labels: Modify

#65 [MODIFY] 애완동물 사진등록, 대표사진, 여러마리 등록, 유효성 검사
  src/components/User/RegisterContext.jsx
  src/components/User/Step1.jsx
  src/components/User/Step2.jsx
  src/components/User/Step3.jsx
  src/components/User/Step4.jsx
  src/components/User/Step5.jsx
  src/pages/User/Login.jsx
  src/pages/User/Register.jsx
Labels: Refactor, Modify

#69 [FIX] App.jsx 관리자쪽 수정
  src/App.jsx
Labels: Fix

#84 [FEAT] 로그인/회원가입 처리 관련 임시구현
  src/App.jsx
  src/components/Global/Header.jsx
  src/components/User/DebugInfo.jsx
  src/components/User/OAuth2Success.jsx
  src/components/User/ProtectedRoute.jsx
  src/components/User/RegisterContext.jsx
  src/components/User/Step1.jsx
  src/components/User/Step5.jsx
  src/pages/User/Login.jsx
Labels: Feat

#85 [FEAT]1차 펫시터 등록페이지
  src/App.jsx
  src/pages/Sitter/PetSitterRegister.jsx
  src/pages/User/MyPage.jsx
Labels: Feat

#96 [FEAT] 관리자 로그인 부트연결 1차
  src/App.jsx
  src/components/Admin/AdminContext.jsx
  src/components/Admin/Layout.jsx
  src/components/Admin/Login.jsx
  src/components/Admin/ProtectedAdminRoute.jsx
Labels: Feat

#91 [FEAT] 임시보호자 찾기/목록 페이지
  public/mock/Sitter/images/sitter1.jpg
  public/mock/Sitter/images/sitter10.jpg
  public/mock/Sitter/images/sitter2.jpg
  public/mock/Sitter/images/sitter3.jpg
  public/mock/Sitter/images/sitter4.jpg
  public/mock/Sitter/images/sitter5.jpg
  public/mock/Sitter/images/sitter6.jpg
  public/mock/Sitter/images/sitter7.jpg
  public/mock/Sitter/images/sitter8.jpg
  public/mock/Sitter/images/sitter9.jpg
  src/App.jsx
  src/components/Global/Footer.jsx
  src/components/Sitter/PetSitterDetail.jsx
  src/components/Sitter/PetSitterResults.jsx
  src/components/Sitter/PetSitterSurvey.jsx
  src/mock/Sitter/petsitters.json
  src/pages/Sitter/PetSitterFinder.jsx
  src/pages/Sitter/PetSitterRegister.jsx
Labels: Feat

#97 [MODIFY] 펫시터 상세보기 페이지
  src/App.jsx
  src/components/Sitter/PetSitterDetail.jsx
  src/components/Sitter/PetSitterResults.jsx
  src/pages/Sitter/PetSitterDetail.jsx
Labels: Modify

#100 [FEAT] 알람페이지 추가, 캘린더 카드 폼 간격수정,클라우드 서버용 프록시 설정, 소셜로그인 버튼 수정
  package-lock.json
  package.json
  src/App.jsx
  src/assets/images/User/naver-logo2.png
  src/components/Calender/CalendarRendering.jsx
  src/components/Calender/DaumPost.jsx
  src/components/Calender/ScheduleFormCard.jsx
  src/components/User/OAuth2Success.jsx
  src/components/User/ProtectedRoute.jsx
  src/components/User/RegisterContext.jsx
  src/components/User/SocialLogin.jsx
  src/components/User/Step1.jsx
  src/components/User/Step2.jsx
  src/components/User/Step3.jsx
  src/components/User/Step4.jsx
  src/mock/Calendar/reserves.json
  src/mock/Calendar/schedules.json
  src/mock/Notification/notification.json
  src/pages/Calender/Cal.jsx
  src/pages/Notification/Notification.jsx
  src/pages/User/Login.jsx
  vite.config.js
Labels: Feat

#105 [FIX] admin 로그인 수정
  src/App.jsx
  src/assets/images/Admin/dog.svg
  src/components/Admin/AdminContext.jsx
  src/components/Admin/Login.jsx
  src/pages/Admin/Admin.jsx
Labels: Fix

#101 [FEAT] 편의시설 목록, 업체 상세보기 페이지 추가 및 UI 수정
  package-lock.json
  package.json
  public/mock/Reserve/arrow.svg
  public/mock/Reserve/facility01.svg
  public/mock/Reserve/review01.svg
  public/mock/Reserve/review02.svg
  src/App.jsx
  src/assets/images/Global/arrow.svg
  src/assets/images/Reserve/map-pin.svg
  src/assets/images/Reserve/payment-success.svg
  src/components/Reserve/card/ReserveCard.jsx
  src/components/Reserve/filter/SortFilter.jsx
  src/components/Reserve/hooks/useInTimeRange.js
  src/components/Reserve/hooks/useReserveFilter.js
  src/components/Reserve/list/ReserveList.jsx
  src/components/Reserve/map/ReserveMap.jsx
  src/components/Reserve/tabs/CategoryTabs.jsx
  src/css/reserve/card.css
  src/css/reserve/detail.css
  src/css/reserve/filter.css
  src/css/reserve/list.css
  src/css/reserve/map.css
  src/css/reserve/reserve.css
  src/css/reserve/tabs.css
  src/mock/Reserve/reserve.json
  src/mock/Reserve/reserveDetail.json
  src/pages/Reserve/Reserve.jsx
  src/pages/Reserve/ReserveDetail.jsx
Labels: Feat

#111 [ADD] 예약 목록, 예약 상세 페이지 추가
  src/App.jsx
  src/components/Reserve/map/ReserveMap.jsx
  src/components/Reserve/utils/CustomizedDot.jsx
  src/mock/Reserve/reserveList.json
  src/pages/Reserve/ReservationDetail.jsx
  src/pages/Reserve/ReservationList.jsx
Labels: Feat

#110 [FEAT]북마크 조회/상세보기
  src/App.jsx
  src/mock/Bookmark/bookmarkData.json
  src/pages/User/Bookmark.jsx
  src/pages/User/PetstaBookmarks.jsx
  src/pages/User/PostBookmarks.jsx
Labels: Feat

#122 [FIX] 게시글 관리 페이지 화면 수정
  src/App.jsx
  src/components/Admin/AdminBoardApi.js
  src/components/Admin/AdminContext.jsx
  src/components/Admin/AdminLayout.jsx
  src/components/Admin/DashBoard.jsx
  src/components/Admin/ProtectedAdminRoute.jsx
  src/components/Admin/ProtectedAdminRoute2.jsx
  src/pages/Admin/TestPage.jsx
Labels: Fix

#126 [FEAT] 내 예약목록, 예약상세, 결제성공, 리뷰작성 페이지 추가
  src/App.jsx
  src/components/Reserve/result/ReservationSuccess.jsx
  src/components/Reserve/utils/BasicModal.jsx
  src/components/Reserve/utils/FileUploader.jsx
  src/components/Reserve/utils/StarRatingConstructor.jsx
  src/mock/Reserve/reserveList.json
  src/pages/Reserve/Reservation.jsx
  src/pages/Reserve/ReservationDetail.jsx
  src/pages/Reserve/Reserve.jsx
  src/pages/Reserve/Review.jsx
Labels: Feat

#139 [FEAT] 공지 작성 1차
  src/components/Admin/AdminBoardApi.js
  src/components/Admin/AdminContext.jsx
  src/components/Admin/DashBoard.jsx
  src/components/Admin/Notice.jsx
  src/components/Admin/PostDetail.jsx
Labels: Feat

#144 [FEAT] 펫시터 목록 1차
  src/components/Admin/AdminPetSitterApi.js
  src/components/Admin/DashBoard.jsx
  src/components/Admin/PetsitterList.jsx
Labels: Feat

#146 [Modify]2차 마이페이지 조회/수정/추가/삭제
  src/pages/User/AddPet.jsx
  src/pages/User/EditPet.jsx
  src/pages/User/MyPage.jsx
Labels: Modify

#147 [FEAT] 펫시터/게시판 목록 썸네일 표시
  src/components/Admin/DashBoard.jsx
  src/components/Admin/PetsitterList.jsx
Labels: Feat

#150 [FEAT] 펫시터 목록 상세보기
  src/components/Admin/AdminBoardApi.js
  src/components/Admin/AdminContext.jsx
  src/components/Admin/AdminLayout.jsx
  src/components/Admin/AdminPetSitterApi.js
  src/components/Admin/DashBoard.jsx
  src/components/Admin/PetSitterDetail.jsx
  src/components/Admin/PetsitterList.jsx
  src/components/Admin/ProtectedAdminRoute.jsx
Labels: Feat

#156 [FEAT] 펫시터 신청목록/상세보기 구현
  src/App.jsx
  src/components/Admin/AdminPetSitterApi.js
  src/components/Admin/Layout.jsx
  src/components/Admin/PetSitterApply.jsx
  src/components/Admin/PetSitterApplyList.jsx
  src/components/Admin/PetSitterDetail.jsx
Labels: Feat

#165 [FEAT] 펫시터 승인/반려/삭제 구현
  src/components/Admin/PetSitterApply.jsx
  src/components/Admin/PetSitterDetail.jsx
Labels: Feat

#172 [FEAT] 게시판/펫시터 검색 기능 구현
  src/App.jsx
  src/components/Admin/PetSitterApplyList.jsx
  src/components/Admin/PetsitterList.jsx
Labels: Feat

#178 [MODIFY] 1차 구현 마이페이지 펫시터 신청 및 그만두기
  src/pages/Sitter/PetSitterRegister.jsx
  src/pages/User/MyPage.jsx
  src/pages/User/PetSitterQuitModal.jsx
Labels: Modify

#199 [MODIFY] 마이페이지 수정 및 펫시터 승인 대기중
  src/components/Sitter/common/OptionCheckboxGroup.jsx
  src/components/Sitter/common/StepButtons.jsx
  src/components/Sitter/common/StepProgress.jsx
  src/components/Sitter/steps/AgeSelectionStep.jsx
  src/components/Sitter/steps/CommentStep.jsx
  src/components/Sitter/steps/CompletionStep.jsx
  src/components/Sitter/steps/ExperienceStep.jsx
  src/components/Sitter/steps/HousingTypeStep.jsx
  src/components/Sitter/steps/PetCountStep.jsx
  src/components/Sitter/steps/PetOwnershipStep.jsx
  src/components/Sitter/steps/PetTypeStep.jsx
  src/components/Sitter/steps/ProfileUploadStep.jsx
  src/components/Sitter/utils/petSitterUtils.js
  src/components/User/Profile/PetListSection.jsx
  src/components/User/Profile/PetSitterSection.jsx
  src/components/User/Profile/UserProfileSection.jsx
  src/pages/Sitter/PetSitterFinder.jsx
  src/pages/Sitter/PetSitterRegister.jsx
  src/pages/User/MyPage.jsx
  src/pages/User/PetSitterQuitModal.jsx
Labels: Modify

#200 [FEAT] 업체등록 페이지 1차
  src/components/Admin/AdminFacilityApi.js
  src/components/Admin/DashBoard.jsx
  src/components/Admin/FacilityAdd.jsx
  src/components/Admin/FacilityDetail.jsx
  src/components/Admin/PetSitterApply.jsx
  src/components/Admin/PetSitterDetail.jsx
  src/components/Admin/PostDetail.jsx
Labels: Feat

#219 [MODIFY]펫시터 목록 찾기
  src/App.jsx
  src/components/Sitter/PetSitterResults.jsx
  src/pages/Sitter/PetSitterDetail.jsx
  src/pages/Sitter/PetSitterFinder.jsx
  src/services/petSitterService.js
Labels: Modify

#222 [FIX] 시설 목록 UI 수정
  package-lock.json
  package.json
  src/components/Payment/FilterSection.jsx
  src/components/Payment/PaymentHistory.jsx
  src/components/Payment/PaymentHistoryItem.jsx
  src/components/Payment/hooks/usePaymentsData.jsx
  src/components/Reserve/card/ReserveCard.jsx
  src/components/Reserve/content/CardContentAboutTime.jsx
  src/components/Reserve/content/FacilityCards.jsx
  src/components/Reserve/content/ListContent.jsx
  src/components/Reserve/filter/CategoryFilter.jsx
  src/components/Reserve/filter/SortFilter.jsx
  src/components/Reserve/hooks/useInTimeRange.js
  src/components/Reserve/hooks/useReserveFilter.js
  src/components/Reserve/list/ReserveList.jsx
  src/components/Reserve/tabs/CategoryTabs.jsx
  src/context/ReserveContext.jsx
  src/css/reserve/card.css
  src/css/reserve/filter.css
  src/css/reserve/list.css
  src/css/reserve/map.css
  src/css/reserve/reserve.css
  src/css/reserve/tabs.css
  src/hook/Reserve/getOpenTime.js
  src/hook/Reserve/isInOpenTimeRange.js
  src/hook/Reserve/useGeolocation.js
  src/hook/Reserve/useInTimeRange.js
  src/hook/Reserve/useInfiniteScroll.js
  src/hook/Reserve/useScrollRestore.js
  src/hook/Reserve/useTodayTimer.js
  src/pages/Reserve/Reserve.jsx
  src/pages/Reserve/ReserveDetail.jsx
  src/services/reserveService.js
Labels: Fix
